/** Offline demo copy for Taleem — Kashmir youth, Roman Urdu */

export const DEMO_HUNARMAND_IDEA = `Acha idea hai — Kashmir mein apple zyada hai aur processing kam, is liye juice/puree ki demand real hai. Competition: local sharbat brands aur imported juices. Pehla qadam: chhota pilot batch banayein, FSSAI basic registration aur packaging label dekhein. Agla: PM Mudra / Mission YUVA type schemes ke liye apna business plan ek page par likhein — Hunarmand schemes section mein apni umar aur zila bata kar dekhein.`

export const DEMO_HUNARMAND_SCHEMES = `Aapki umar aur business ke hisaab se yeh dekhein: PM Mudra (shuruati loan), Mission YUVA / YUVA schemes (youth), J&K startup / DIC portals. Pehla qadam: zila DIC ya CSC par basic Udyam registration. Mentor se mil kar application ke form bharna seekhein — yahan "Mentor connect" se rabta karein.`

export const DEMO_SUKOON_CHECKIN = `Sun pa raha hoon — naukri na milne ki frustration waqai dukh hoti hai, aap akelay nahi hain. Teen lambi saans: 4 hisaab andar, 4 ruk kar, 4 bahar. Aaj sirf ek chhota qadam: Kaam Dhundo mein apni skill bata kar dekhein. Agar dil zyada bhari lage to neeche helpline ek tap door hai — madad mangna himmat hai.`

export const DEMO_KAAM_SKILL = `Aap phone repair jaante hain — yeh "Mobile / electronics repair technician" category mein aata hai. Nazdeek Sopore / Baramulla mein chhote mobile shops aksar helper chahti hain; hafte mein ek dukan par haazir ho kar poochh sakte hain. Online: Fiverr / local Facebook groups par "screen replacement" jaise services se shuruat. Main Freelance guide tab mein profile banana step-by-step bata sakta hoon.`

export const DEMO_KAAM_GIG = `Aaj ke demo gigs (Urdu voice): (1) Delivery partner — flexible hours, app se apply. (2) Tourism season mein local guide / homestay help. (3) Remote: chhota data entry / transcription — Rozgar portals aur trusted Facebook groups dekhein. Har gig ke liye pehle malik ka naam aur pata verify karein — advance paise na dein.`

export const DEMO_KAAM_FREELANCE = `Fiverr pe pehla step: account banaein, profile photo seedha rakhein, Urdu mein soch kar English mein 3 line service likhein — jaise "I fix software issues on Android phones". Pehli gig: $5 wali simple service taake review aaye. Upwork thoda mushkil — Fiverr se shuru karna aasaan. Roz 30 minute profile improve karein.`

export const DEMO_NAUKRI = `Aapki qualification ke hisaab se (demo): JKSSB Class IV / Panchayat Secretary jaisi ads kabhi kabhi aati hain — deadline calendar mein daal kar taiyaari shuru karein. Police / forest recruitment alag portal hoti hain. Agla qadam: jkssb.nic.in aur official J&K notices dekhein. Exam prep tab rozana sawal ke saath practice karein.`

export const DEMO_CV = `CURRICULUM VITAE (English — from your Urdu voice)\n\nNAME: [Your name]\nLOCATION: Kashmir, India\n\nPROFILE\nHard-working youth with practical skills and a strong wish to learn. Comfortable helping people and working in a team.\n\nEXPERIENCE\n— Informal / family work and local volunteering (describe briefly).\n\nSKILLS\n— Communication in Urdu / Hindi; basic smartphone and computer use; quick learner.\n\nEDUCATION\n— [Add your class / college]\n\nLANGUAGES\n— Urdu, Hindi, English (basic / intermediate as fits)\n\nREFERENCES\nAvailable on request.\n\n— Generated by RAASTA Taleem (demo). Edit names and dates before sending.`

export const DEMO_EXAM_FEEDBACK = `Theek hai — jawab ka asal hisaab examiners ke marking scheme se juda hota hai. Aapne main point chhua — General Knowledge ke liye rozana 10 sawal aur current affairs padhein. Agla: JKSSB syllabus PDF se ek topic choose kar ke us par 5 minute loud revision karein.`

export const DEMO_SCHOLARSHIP = `Marks ~78% Science (demo OCR) ke saath yeh dekhein: National Scholarship Portal (means / merit), state post-matric schemes, aur khaas tor par minority / tribal scholarships agar laagu hon. Deadlines aksar September–November hoti hain — NSP par account jaldi banayein. College office se "income certificate" aur bank account seedha rakhein. Yeh mashwara hai — official eligibility hamesha portal par check karein.`
